# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tracker_packet_pb2 as tracker__packet__pb2


class TrackerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPacketArrayStream = channel.unary_stream(
                '/tracker.TrackerService/GetPacketArrayStream',
                request_serializer=tracker__packet__pb2.TrackerPacketRequest.SerializeToString,
                response_deserializer=tracker__packet__pb2.TrackerPacketArrayStreamResponse.FromString,
                )


class TrackerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPacketArrayStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPacketArrayStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPacketArrayStream,
                    request_deserializer=tracker__packet__pb2.TrackerPacketRequest.FromString,
                    response_serializer=tracker__packet__pb2.TrackerPacketArrayStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracker.TrackerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrackerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPacketArrayStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tracker.TrackerService/GetPacketArrayStream',
            tracker__packet__pb2.TrackerPacketRequest.SerializeToString,
            tracker__packet__pb2.TrackerPacketArrayStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
